apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: silicon-tls
spec:
  secretName: silicon-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - silicon-ctf.party
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - silicon-ctf.party