apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqllite-pv-claim
  namespace: rootthebox
  labels:
    app: rootthebox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi