apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-var-pv-claim
  namespace: splunk
  labels:
    app: splunk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-etc-pv-claim
  namespace: splunk
  labels:
    app: splunk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi